### ISSUE TITLE
capitalize first letter of each city word upon rendering to databox

### ISSUE THREAD

**Issue by mat-lundin** [nicoledodge/Project1#39]

**Comment by JAMATX38** [comment]
https://flexiple.com/javascript-capitalize-first-letter/

Dropping here to reference later.

**Comment by JAMATX38** [comment]
![capitalize first letter](https://user-images.githubusercontent.com/90355259/136068707-049666aa-b8f3-4880-855f-1f9c0798ef6d.JPG)
